apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-host
spec:
  rules:
  - host: 
    http:
      paths: /addressbook-1.0
      - pathType: Prefix
        path: 
        backend:
          service:
            name:
            port:
              number: 8080
  - host: 
    http:
      paths:/addressbook-1.0
      - pathType: Prefix
        path: 
        backend:
          service:
            name: addressbook-service
            port:
              number: 8080
