apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-host
spec:
  rules:
  - host: 
    http:
      paths:
      - path: /addressbook-1.0
        pathType: Prefix
        backend:
          service:
            name: addressbook-service # Add the correct service name here
            port:
              number: 8080
  - host: 
    http:
      paths:
      - path: /addressbook-1.0
        pathType: Prefix
        backend:
          service:
            name: addressbook-service
            port:
              number: 8080
